//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssignmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        public string TraineeID { get; set; }
        public string TraineeName { get; set; }
        public System.DateTime DoB { get; set; }
        public string Education { get; set; }
        public string ProgrammingLanguage { get; set; }
        public Nullable<int> TOEIC { get; set; }
        public int ExperienceYear { get; set; }
        public string Address { get; set; }

        public List<Trainee> ListTrainee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
